modLoader = "javafml"
loaderVersion = "[4,)"
license = "All rights reserved"

[[mods]]
modId = "tinycorelib"
version = "${mod_version}"
displayName = "Tiny Core Lib"
authors = "Tiny"

[[mixins]]
config = "tinycorelib.mixins.json"

[[dependencies.tinycorelib]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinycorelib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"
