modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId = "tinydatagen"
version = "${mod_version}"
displayName = "Tiny DataGen Lib"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="tinycorelib.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors = "Tiny"

[[dependencies.tinydatagen]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tinydatagen]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"

